# Generated by Django 5.1.5 on 2025-02-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExportedGoods', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=100)),
                ('CompanyAddress', models.CharField(max_length=200)),
                ('CompanyType', models.CharField(max_length=50)),
                ('CompanyStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfficeName', models.CharField(max_length=100)),
                ('BranchName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegistrationNumber', models.CharField(max_length=50)),
                ('CertificateNumber', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('IssueDate', models.DateField()),
                ('ReceiptNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('ReceiptDate', models.DateField(blank=True, null=True)),
                ('PaymentAmount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ExportedGoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificate_app.cargo')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.company')),
                ('ExportCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_country_certificates', to='certificate_app.country')),
                ('OriginCountry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_country_certificates', to='certificate_app.country')),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate_app.office')),
            ],
        ),
    ]
