# Generated by Django 5.1.5 on 2025-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='office',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveIndex(
            model_name='certificate',
            name='certificate_BranchN_05dd90_idx',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='BranchName',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
