# Generated by Django 5.1.5 on 2025-02-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_alter_certificate_quantity_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='BranchName',
        ),
    ]
