# Generated by Django 5.1.5 on 2025-04-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_branch_certificate_branch_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='office',
        ),
    ]
