# Generated by Django 5.1.5 on 2025-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0004_remove_branch_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_branch_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_branch_user',
        ),
    ]
