# Generated by Django 5.1.5 on 2025-04-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0005_remove_userprofile_is_branch_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_add_certificates',
            field=models.BooleanField(default=False),
        ),
    ]
