# Generated by Django 5.1.5 on 2025-04-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0006_userprofile_can_add_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_admin', 'Branch Admin'), ('branch_user', 'Branch User')], default='branch_user', max_length=20),
        ),
    ]
