# Generated by Django 5.1.5 on 2025-04-29 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0007_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_add_certificates',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
