# Generated by Django 5.1.5 on 2025-04-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0008_remove_userprofile_can_add_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_branch_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_branch_user',
            field=models.BooleanField(default=False),
        ),
    ]
