# Generated by Django 5.1.5 on 2025-05-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0009_userprofile_is_branch_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate_app.branch', verbose_name='الفرع'),
        ),
    ]
