# Generated by Django 5.1.5 on 2025-05-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0010_alter_certificate_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='Branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='certificate_app.branch'),
        ),
    ]
