# Generated by Django 5.1.5 on 2025-05-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0011_alter_certificate_branch'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(condition=models.Q(('RegistrationNumber__isnull', False), models.Q(('RegistrationNumber', 'غير موجود'), _negated=True)), fields=('Office', 'RegistrationNumber'), name='unique_office_registration'),
        ),
    ]
