# Generated by Django 5.1.5 on 2025-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0013_remove_certificate_unique_office_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='CertificateNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
