# Generated by Django 5.1.5 on 2025-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0014_alter_certificate_certificatenumber'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='certificate',
            name='unique_branch_office_reg_cert',
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.UniqueConstraint(fields=('Branch', 'CertificateNumber'), name='unique_branch_certificate'),
        ),
    ]
