# Generated by Django 5.1.5 on 2025-02-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='CertificateNumber',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='RegistrationNumber',
            field=models.CharField(max_length=50),
        ),
    ]
