# Generated by Django 5.1.5 on 2025-02-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0002_certificate_certificatenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='RegistrationNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
