# Generated by Django 5.1.5 on 2025-02-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_app', '0003_alter_certificate_registrationnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='RegistrationNumber',
            field=models.CharField(max_length=50),
        ),
    ]
